version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ent
      - MYSQL_USER=ent
      - MYSQL_PASSWORD=ent
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"