header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - hz/**
    - render/protobuf/body/body.pb.go
    - tracer/kitex/kitex_gen/**
    - opentelemetry/kitex/kitex_gen/**
    - hz_kitex_demo/**
    - bizdemo/hertz_gorm/biz/hertz_gen/**
    - bizdemo/hertz_gorm/biz/router/**
    - bizdemo/hertz_gorm/router_gen.go
    - bizdemo/hertz_jwt/biz/router/**
    - bizdemo/hertz_jwt/router_gen.go
    - bizdemo/hertz_gorm_gen/biz/model/api/**
    - bizdemo/hertz_gorm_gen/biz/model/hertz/**
    - bizdemo/hertz_gorm_gen/biz/model/orm_gen/**
    - bizdemo/hertz_gorm_gen/biz/model/query/**
    - bizdemo/hertz_gorm_gen/biz/router/**
    - bizdemo/hertz_gorm_gen/router_gen.go
    - bizdemo/hertz_session/biz/model/**
    - bizdemo/hertz_session/biz/router/**
    - bizdemo/hertz_session/router_gen.go
    - bizdemo/hertz_swagger_gen/**
    - hz_client/**

  comment: on-failure