header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - hz/**
    - render/protobuf/body/body.pb.go
    - tracer/kitex/kitex_gen/**
    - opentelemetry/kitex/kitex_gen/**
    - hz_kitex_demo/**
    - tls/server.crt
    - tls/server.key

  comment: on-failure