init_api:
	hz new --mod=github.com/hertz/hello --idl=idl/hello.thrift --customize_package=template/package.yaml: --customize_layout=template/layout.yaml:

update_api:
	hz update --mod=github.com/hertz/hello --idl=idl/hello.thrift --customize_package=template/package.yaml: --customize_layout=template/layout.yaml:
