// Code generated by hertz generator.

package Api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _insertstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querystudentMw() []app.HandlerFunc {
	// your code...
	return nil
}
