// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)
var _ = descriptorpb.File_google_protobuf_descriptor_proto
