/*
 * Copyright 2022 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"hertz-examples/bizdemo/hertz_session/biz/consts"
	"hertz-examples/bizdemo/hertz_session/biz/handler"
	"hertz-examples/bizdemo/hertz_session/biz/handler/hertz_session"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	// store session in redis
	store, err := redis.NewStore(consts.MaxIdleNum, consts.TCP, consts.RedisAddr, consts.RedisPasswd, []byte(consts.SecretKey))
	if err != nil {
		panic(err)
	}
	// use session middleware
	r.Use(sessions.Sessions(consts.HertzSession, store))
	r.POST("/register", hertz_session.Register)
	r.POST("/login", hertz_session.Login)
	r.GET("/page", hertz_session.Page)
}
