/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:PK" json:"id"`                                                // PK
	Name      string         `gorm:"column:name;not null;comment:User name" json:"name"`                                                          // User name
	Gender    int32          `gorm:"column:gender;not null;comment:User gender" json:"gender"`                                                    // User gender
	Age       int32          `gorm:"column:age;not null;comment:User age" json:"age"`                                                             // User age
	Introduce string         `gorm:"column:introduce;comment:User introduce" json:"introduce"`                                                    // User introduce
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:User information create time" json:"created_at"` // User information create time
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:User information update time" json:"updated_at"` // User information update time
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:User information delete time" json:"deleted_at"`                                    // User information delete time
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
