init_user:
	hz new --model_dir biz/hertz_gen -mod github.com/cloudwego/hertz-examples/bizdemo/hertz_swagger_gen -thrift-plugins=http-swagger -idl idl/user.thrift


update_user:
	hz update --model_dir biz/hertz_gen -thrift-plugins=http-swagger -idl idl/user.thrift