// Code generated by hertz generator.

package UserGorm

import (
	"os"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/jwt"
)

var jwtMiddleware *jwt.HertzJWTMiddleware

func init() {
	key := os.Getenv("JWT_SECRET_KEY")
	if key == "" {
		// In development/demo, warn but don't block
		key = "demo-temporary-key-change-in-production"
	}
	jwtMiddleware, _ = jwt.New(&jwt.HertzJWTMiddleware{
		Key:         []byte(key),
		TokenLookup: "header: Authorization",
		TokenHeadName: "Bearer",
	})
}

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{gzip.Gzip(gzip.DefaultCompression)}
}

func _v1Mw() []app.HandlerFunc {
	return nil
}

func _userMw() []app.HandlerFunc {
	return nil
}

func _createMw() []app.HandlerFunc {
	return nil
}

func _createuserMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwtMiddleware.MiddlewareFunc()}
}

func _deleteMw() []app.HandlerFunc {
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwtMiddleware.MiddlewareFunc()}
}

func _queryMw() []app.HandlerFunc {
	return nil
}

func _queryuserMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwtMiddleware.MiddlewareFunc()}
}

func _updateMw() []app.HandlerFunc {
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwtMiddleware.MiddlewareFunc()}
}
