// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	hzClient "hertz-examples/hz_client/server/biz/model/toutiao/middleware/hzClient"
)

// BodyMethod .
// @router /body [POST]
func BodyMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hzClient.BodyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	fmt.Println("req:")
	fmt.Println(req)

	resp := new(hzClient.Resp)
	resp.Resp = "this is body method"

	c.JSON(200, resp)
}
