// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/darrenli6/hertz-examples/bizdemo/hertz_casbin/biz/dal"
	"github.com/darrenli6/hertz-examples/bizdemo/hertz_casbin/biz/mw"
)

func Init(h *server.Hertz) {
	dal.Init()
	mw.InitCasbin()

}

func main() {
	h := server.Default()
	Init(h)
	register(h)
	h.Spin()
}
