// Code generated by Kitex v0.3.2. DO NOT EDIT.
package studentmanagement

import (
	"github.com/cloudwego/kitex/server"
	"hertz-examples/hz_demo/hertz-server/kitex_gen/student/management"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler management.StudentManagement, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
