// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: body.proto

package body

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BodyStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []byte `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (x *BodyStruct) Reset() {
	*x = BodyStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyStruct) ProtoMessage() {}

func (x *BodyStruct) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyStruct.ProtoReflect.Descriptor instead.
func (*BodyStruct) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{0}
}

func (x *BodyStruct) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_body_proto protoreflect.FileDescriptor

var file_body_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0x20, 0x0a, 0x0a, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x62, 0x6f, 0x64, 0x79,
}

var (
	file_body_proto_rawDescOnce sync.Once
	file_body_proto_rawDescData = file_body_proto_rawDesc
)

func file_body_proto_rawDescGZIP() []byte {
	file_body_proto_rawDescOnce.Do(func() {
		file_body_proto_rawDescData = protoimpl.X.CompressGZIP(file_body_proto_rawDescData)
	})
	return file_body_proto_rawDescData
}

var file_body_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_body_proto_goTypes = []interface{}{
	(*BodyStruct)(nil), // 0: body.BodyStruct
}
var file_body_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_body_proto_init() }
func file_body_proto_init() {
	if File_body_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_body_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_body_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_body_proto_goTypes,
		DependencyIndexes: file_body_proto_depIdxs,
		MessageInfos:      file_body_proto_msgTypes,
	}.Build()
	File_body_proto = out.File
	file_body_proto_rawDesc = nil
	file_body_proto_goTypes = nil
	file_body_proto_depIdxs = nil
}
