init_api:
	hz new --mod=github.com/hz/template_render_data --idl=idl/hello.thrift --customize_package=template/package.yaml: --customize_layout=template/layout.yaml:template/layout.json

update_api:
	hz update --mod=github.com/hz/template_render_data --idl=idl/hello.thrift --customize_package=template/package.yaml: --customize_layout=template/layout.yaml:template/layout.json
