// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // PK
	Name      string         `gorm:"column:name;not null" json:"name"`                                       // User name
	Gender    int32          `gorm:"column:gender;not null" json:"gender"`                                   // User gender
	Age       int32          `gorm:"column:age;not null" json:"age"`                                         // User age
	Introduce string         `gorm:"column:introduce" json:"introduce"`                                      // User introduce
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // User information create time
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // User information update time
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // User information delete time
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
