name: Pull Request Check

on: [pull_request]

jobs:
  compliant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0

      - name: typos-action
        uses: crate-ci/typos@master
