name: Pull Request Check

on: [pull_request]

jobs:
  compliant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0

      - name: typos-action
        uses: crate-ci/typos@master

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          # For self-hosted, the cache path is shared across projects
          # And it works well without the cache of GitHub actions
          # Enable it if we're going to use GitHub only
          cache: true

      - name: Golangci Lint
        # https://golangci-lint.run/
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: true